{% set version = "0.5.3" %}

package:
  name: rdflib-sqlalchemy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/rdflib-sqlalchemy/rdflib-sqlalchemy-{{ version }}.tar.gz
  sha256: a7a2e83d113db8e879477074ffac10b589d96c84007ad6ed067d1b8762d61e74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - alembic >=0.8.8
    - python >={{ python_min }}
    - rdflib >=4.0
    - six >=1.10.0
    - sqlalchemy >=1.1.4

test:
  source_files:
    - test
  imports:
    - rdflib_sqlalchemy
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://github.com/RDFLib/rdflib-sqlalchemy
  summary: rdflib extension adding SQLAlchemy as an AbstractSQLStore back-end store
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
